### PR TITLE
Expose errors to exceptions

### PR DESCRIPTION
**Pull request by Alphadelta14**
Ensure that the errors raised have some meaning to them. There was an issue where `get_errno` would always return 0. This fixes those issues.

### CODE REVIEW

**Comment by justinclift** [comment]
This sounds like a good idea. :smile:

(Note - I'm not a code reviewer for this project)

**Comment by prashanthpai** [comment]
@Alphadelta14 This looks great! Thank you for the PR. You fixed BZ 1196161.

This github repo is only a mirror and all our development happens over Gluster Gerrit (http://review.gluster.org/#/q/project:libgfapi-python). It would be really nice if you could send this change to Gerrit instead for easier review. This way you can continue to contribute by following the normal workflow followed by the project. However, if you do not have time for the same, I can do it for you. Let me know.

Thanks!

**Comment by prashanthpai** [comment]
The Development Workflow: https://github.com/gluster/libgfapi-python/blob/master/doc/markdown/dev_guide.md

**Comment by Alphadelta14** [comment]
@prashanthpai Thank you for your patience. I have re-submitted for review on Gerrit.

**Pull request closed without merging**
